const dashboardIntialState = {
  getStudentDashboardData: [],
  getStudentDashboardDataLoading: false,
  profileUpdateLoading: false,
  profileUpdatedData: "",
  mentorBatches: [],
  mentorBatchesLoading: false,
  mentorStudentList: [],
  mentorStudentListLoading: false,
  mentorDashboardData: [],
  mentorDashboardDataLoading: false,
  mentorDashboardAssignmentList: [],
  mentorDashboardAssignmentListLoading: false,
  getSubmittedAssignemntList: [],
  getSubmittedAssignemntListLoading: false,
  studentUpcomingTasks: [],
  studentUpcomingTaskLoading: false,
  studentBatchMates: [],
  studentBatchMatesLoading: false,
  studentAssignmentList: [],
  studentAssignmentListLoading: false,
  getStudentProgress: [],
  getStudentProgressLoading: false,
  getStudentCourseDetails: [],
  getStudentCourseDetailsLoading: false,
  mentorUpcomingTask: [],
  mentorUpcomingTasksLoading: false,
  updateScoreLoading: false
};
export default dashboardIntialState;
