export const country_list = [
  {
    id: 225,
    country_code: "AE",
    name: "United Arab Emirates",
    dial_code: "+971",
    value: 183,
    currency: "AED",
    country_delivery_group_id: 1,
    continent: "Asia",
    currency_symbol: "د.إ",
    top_country: true,
    nationality: "Emirati",
    all_inclusive: 1
  },
  {
    id: 187,
    country_code: "SA",
    name: "Saudi Arabia",
    dial_code: "+966",
    value: 151,
    currency: "SAR",
    country_delivery_group_id: 3,
    continent: "Asia",
    currency_symbol: "ر.س",
    top_country: true,
    nationality: "Saudi",
    all_inclusive: 1
  },
  {
    id: 1,
    country_code: "US",
    name: "United States",
    dial_code: "+1",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 4,
    continent: "North America",
    currency_symbol: "$",
    top_country: true,
    nationality: "American",
    all_inclusive: 0
  },
  {
    id: 176,
    country_code: "QA",
    name: "Qatar",
    dial_code: "+974",
    value: 141,
    currency: "QAR",
    country_delivery_group_id: 3,
    continent: "Asia",
    currency_symbol: "ر.ق",
    top_country: false,
    nationality: "Qatari",
    all_inclusive: 1
  },
  {
    id: 5,
    country_code: "DZ",
    name: "Algeria",
    dial_code: "+213",
    value: 3,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Algerian",
    all_inclusive: 0
  },
  {
    id: 8,
    country_code: "AO",
    name: "Angola",
    dial_code: "+244",
    value: 5,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Angolan",
    all_inclusive: 0
  },
  {
    id: 12,
    country_code: "AR",
    name: "Argentina",
    dial_code: "+54",
    value: 7,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "South America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Argentinian",
    all_inclusive: 0
  },
  {
    id: 14,
    country_code: "AW",
    name: "Aruba",
    dial_code: "+297",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Aruban",
    all_inclusive: 0
  },
  {
    id: 15,
    country_code: "AU",
    name: "Australia",
    dial_code: "+61",
    value: 9,
    currency: "AUD",
    country_delivery_group_id: 5,
    continent: "Australia",
    currency_symbol: "A$",
    top_country: true,
    nationality: "Australian",
    all_inclusive: 0
  },
  {
    id: 16,
    country_code: "AT",
    name: "Austria",
    dial_code: "+43",
    value: 10,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Austrian",
    all_inclusive: 0
  },
  {
    id: 17,
    country_code: "AZ",
    name: "Azerbaijan",
    dial_code: "+994",
    value: 11,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Azerbaijani",
    all_inclusive: 0
  },
  {
    id: 18,
    country_code: "BS",
    name: "Bahamas",
    dial_code: "+1 242",
    value: 12,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bahamian",
    all_inclusive: 0
  },
  {
    id: 19,
    country_code: "BH",
    name: "Bahrain",
    dial_code: "+973",
    value: 13,
    currency: "BHD",
    country_delivery_group_id: 3,
    continent: "Asia",
    currency_symbol: "ب.د",
    top_country: false,
    nationality: "Bahraini",
    all_inclusive: 1
  },
  {
    id: 20,
    country_code: "BD",
    name: "Bangladesh",
    dial_code: "+880",
    value: 14,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bangladeshi",
    all_inclusive: 0
  },
  {
    id: 23,
    country_code: "BE",
    name: "Belgium",
    dial_code: "+32",
    value: 17,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Belgian",
    all_inclusive: 0
  },
  {
    id: 28,
    country_code: "BO",
    name: "Bolivia",
    dial_code: "+591",
    value: 21,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "South America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bolivian",
    all_inclusive: 0
  },
  {
    id: 29,
    country_code: "BA",
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    value: 22,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bosnian",
    all_inclusive: 0
  },
  {
    id: 30,
    country_code: "BW",
    name: "Botswana",
    dial_code: "+267",
    value: 23,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Batswana",
    all_inclusive: 0
  },
  {
    id: 34,
    country_code: "BN",
    name: "Brunei Darussalam",
    dial_code: "+673",
    value: 25,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bruneian",
    all_inclusive: 0
  },
  {
    id: 35,
    country_code: "BG",
    name: "Bulgaria",
    dial_code: "+359",
    value: 26,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Bulgarian",
    all_inclusive: 0
  },
  {
    id: 36,
    country_code: "BF",
    name: "Burkina Faso",
    dial_code: "+226",
    value: 27,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Burkinabe",
    all_inclusive: 0
  },
  {
    id: 38,
    country_code: "KH",
    name: "Cambodia",
    dial_code: "+855",
    value: 30,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Cambodian",
    all_inclusive: 0
  },
  {
    id: 2,
    country_code: "CA",
    name: "Canada",
    dial_code: "+1",
    value: 32,
    currency: "CAD",
    country_delivery_group_id: 4,
    continent: "North America",
    currency_symbol: "C$",
    top_country: true,
    nationality: "Canadian",
    all_inclusive: 0
  },
  {
    id: 41,
    country_code: "KY",
    name: "Cayman Islands",
    dial_code: "+ 345",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Caymanian",
    all_inclusive: 0
  },
  {
    id: 44,
    country_code: "CL",
    name: "Chile",
    dial_code: "+56",
    value: 36,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "South America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Chilean",
    all_inclusive: 0
  },
  {
    id: 45,
    country_code: "CN",
    name: "China",
    dial_code: "+86",
    value: 37,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Chinese",
    all_inclusive: 0
  },
  {
    id: 48,
    country_code: "CO",
    name: "Colombia",
    dial_code: "+57",
    value: 38,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "South America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Colombian",
    all_inclusive: 0
  },
  {
    id: 53,
    country_code: "HR",
    name: "Croatia (Hrvatska)",
    dial_code: "+385",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Croatian",
    all_inclusive: 0
  },
  {
    id: 55,
    country_code: "CY",
    name: "Cyprus",
    dial_code: "+357",
    value: 46,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Cypriot",
    all_inclusive: 0
  },
  {
    id: 56,
    country_code: "CZ",
    name: "Czech Republic",
    dial_code: "+420",
    value: 47,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Czech",
    all_inclusive: 0
  },
  {
    id: 57,
    country_code: "DK",
    name: "Denmark",
    dial_code: "+45",
    value: 48,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Danish",
    all_inclusive: 0
  },
  {
    id: 63,
    country_code: "EG",
    name: "Egypt",
    dial_code: "+20",
    value: 53,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Egyptian",
    all_inclusive: 0
  },
  {
    id: 64,
    country_code: "SV",
    name: "El Salvador",
    dial_code: "+503",
    value: 54,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Salvadorian",
    all_inclusive: 0
  },
  {
    id: 67,
    country_code: "EE",
    name: "Estonia",
    dial_code: "+372",
    value: 57,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Estonian",
    all_inclusive: 0
  },
  {
    id: 71,
    country_code: "FJ",
    name: "Fiji",
    dial_code: "+679",
    value: 59,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Oceania",
    currency_symbol: "$",
    top_country: false,
    nationality: "Fijian",
    all_inclusive: 0
  },
  {
    id: 72,
    country_code: "FI",
    name: "Finland",
    dial_code: "+358",
    value: 60,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Finnish",
    all_inclusive: 0
  },
  {
    id: 73,
    country_code: "FR",
    name: "France",
    dial_code: "+33",
    value: 61,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "French",
    all_inclusive: 0
  },
  {
    id: 80,
    country_code: "GE",
    name: "Georgia",
    dial_code: "+995",
    value: 64,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Georgian",
    all_inclusive: 0
  },
  {
    id: 81,
    country_code: "DE",
    name: "Germany",
    dial_code: "+49",
    value: 65,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "German",
    all_inclusive: 0
  },
  {
    id: 82,
    country_code: "GH",
    name: "Ghana",
    dial_code: "+233",
    value: 66,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Ghanaian",
    all_inclusive: 0
  },
  {
    id: 84,
    country_code: "GR",
    name: "Greece",
    dial_code: "+30",
    value: 67,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Greek",
    all_inclusive: 0
  },
  {
    id: 88,
    country_code: "GU",
    name: "Guam",
    dial_code: "+1 671",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Oceania",
    currency_symbol: "$",
    top_country: false,
    nationality: "American (Guam)",
    all_inclusive: 0
  },
  {
    id: 96,
    country_code: "HK",
    name: "Hong Kong",
    dial_code: "+852",
    value: 205,
    currency: "HKD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "HK$",
    top_country: true,
    nationality: "Chinese (Hong Kong)",
    all_inclusive: 0
  },
  {
    id: 97,
    country_code: "HU",
    name: "Hungary",
    dial_code: "+36",
    value: 75,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Hungarian",
    all_inclusive: 0
  },
  {
    id: 99,
    country_code: "IN",
    name: "India",
    dial_code: "+91",
    value: 77,
    currency: "INR",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "₹",
    top_country: false,
    nationality: "Indian",
    all_inclusive: 0
  },
  {
    id: 100,
    country_code: "ID",
    name: "Indonesia",
    dial_code: "+62",
    value: 78,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Indonesian",
    all_inclusive: 0
  },
  {
    id: 102,
    country_code: "IQ",
    name: "Iraq",
    dial_code: "+964",
    value: 80,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Iraqi",
    all_inclusive: 0
  },
  {
    id: 103,
    country_code: "IE",
    name: "Ireland",
    dial_code: "+353",
    value: 81,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Irish",
    all_inclusive: 0
  },
  {
    id: 104,
    country_code: "IL",
    name: "Israel",
    dial_code: "+972",
    value: 82,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Israeli",
    all_inclusive: 0
  },
  {
    id: 105,
    country_code: "IT",
    name: "Italy",
    dial_code: "+39",
    value: 83,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Italian",
    all_inclusive: 0
  },
  {
    id: 108,
    country_code: "JP",
    name: "Japan",
    dial_code: "+81",
    value: 85,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Japanese",
    all_inclusive: 0
  },
  {
    id: 244,
    country_code: "JE",
    name: "Jersey",
    dial_code: "+44",
    value: 1,
    currency: "GBP",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "£",
    top_country: false,
    nationality: "Jersey",
    all_inclusive: 0
  },
  {
    id: 109,
    country_code: "JO",
    name: "Jordan",
    dial_code: "+962",
    value: 86,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Jordanian",
    all_inclusive: 0
  },
  {
    id: 110,
    country_code: "KZ",
    name: "Kazakhstan",
    dial_code: "+7",
    value: 87,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Kazakhstani",
    all_inclusive: 0
  },
  {
    id: 116,
    country_code: "KW",
    name: "Kuwait",
    dial_code: "+965",
    value: 92,
    currency: "KWD",
    country_delivery_group_id: 3,
    continent: "Asia",
    currency_symbol: "د.ك",
    top_country: true,
    nationality: "Kuwaiti",
    all_inclusive: 1
  },
  {
    id: 119,
    country_code: "LV",
    name: "Latvia",
    dial_code: "+371",
    value: 95,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Latvian",
    all_inclusive: 0
  },
  {
    id: 120,
    country_code: "LB",
    name: "Lebanon",
    dial_code: "+961",
    value: 96,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Lebanese",
    all_inclusive: 0
  },
  {
    id: 125,
    country_code: "LT",
    name: "Lithuania",
    dial_code: "+370",
    value: 101,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Lithuanian",
    all_inclusive: 0
  },
  {
    id: 126,
    country_code: "LU",
    name: "Luxembourg",
    dial_code: "+352",
    value: 102,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Luxembourgish",
    all_inclusive: 0
  },
  {
    id: 131,
    country_code: "MY",
    name: "Malaysia",
    dial_code: "+60",
    value: 106,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Malaysian",
    all_inclusive: 0
  },
  {
    id: 132,
    country_code: "MV",
    name: "Maldives",
    dial_code: "+960",
    value: 107,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Maldivian",
    all_inclusive: 0
  },
  {
    id: 134,
    country_code: "MT",
    name: "Malta",
    dial_code: "+356",
    value: 109,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Maltese",
    all_inclusive: 0
  },
  {
    id: 138,
    country_code: "MU",
    name: "Mauritius",
    dial_code: "+230",
    value: 112,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Mauritian",
    all_inclusive: 0
  },
  {
    id: 140,
    country_code: "MX",
    name: "Mexico",
    dial_code: "+52",
    value: 113,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Mexican",
    all_inclusive: 0
  },
  {
    id: 143,
    country_code: "MC",
    name: "Monaco",
    dial_code: "+377",
    value: 116,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Monacan",
    all_inclusive: 0
  },
  {
    id: 147,
    country_code: "MA",
    name: "Morocco",
    dial_code: "+212",
    value: 118,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Moroccan",
    all_inclusive: 0
  },
  {
    id: 153,
    country_code: "NL",
    name: "Netherlands",
    dial_code: "+31",
    value: 1,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Dutch",
    all_inclusive: 0
  },
  {
    id: 156,
    country_code: "NZ",
    name: "New Zealand",
    dial_code: "+64",
    value: 125,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Oceania",
    currency_symbol: "$",
    top_country: false,
    nationality: "New Zealand",
    all_inclusive: 0
  },
  {
    id: 159,
    country_code: "NG",
    name: "Nigeria",
    dial_code: "+234",
    value: 128,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Nigerian",
    all_inclusive: 0
  },
  {
    id: 163,
    country_code: "NO",
    name: "Norway",
    dial_code: "+47",
    value: 129,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Norwegian",
    all_inclusive: 0
  },
  {
    id: 164,
    country_code: "OM",
    name: "Oman",
    dial_code: "+968",
    value: 130,
    currency: "OMR",
    country_delivery_group_id: 3,
    continent: "Asia",
    currency_symbol: "ر.ع.",
    top_country: true,
    nationality: "Omani",
    all_inclusive: 0
  },
  {
    id: 165,
    country_code: "PK",
    name: "Pakistan",
    dial_code: "+92",
    value: 131,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Pakistani",
    all_inclusive: 0
  },
  {
    id: 167,
    country_code: "PA",
    name: "Panama",
    dial_code: "+507",
    value: 134,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Panamanian",
    all_inclusive: 0
  },
  {
    id: 171,
    country_code: "PH",
    name: "Philippines",
    dial_code: "+63",
    value: 138,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Philippine",
    all_inclusive: 0
  },
  {
    id: 173,
    country_code: "PL",
    name: "Poland",
    dial_code: "+48",
    value: 139,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Polish",
    all_inclusive: 0
  },
  {
    id: 174,
    country_code: "PT",
    name: "Portugal",
    dial_code: "+351",
    value: 140,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Portuguese",
    all_inclusive: 0
  },
  {
    id: 175,
    country_code: "PR",
    name: "Puerto Rico",
    dial_code: "+1 939",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "North America",
    currency_symbol: "$",
    top_country: false,
    nationality: "Puerto Rican",
    all_inclusive: 0
  },
  {
    id: 114,
    country_code: "KR",
    name: "Republic of Korea",
    dial_code: "+82",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "South Korean",
    all_inclusive: 0
  },
  {
    id: 142,
    country_code: "MD",
    name: "Republic of Moldova",
    dial_code: "+373",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Moldovan",
    all_inclusive: 0
  },
  {
    id: 178,
    country_code: "RO",
    name: "Romania",
    dial_code: "+40",
    value: 142,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Romanian",
    all_inclusive: 0
  },
  {
    id: 189,
    country_code: "RS",
    name: "Serbia",
    dial_code: "+381",
    value: 153,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Serbian",
    all_inclusive: 0
  },
  {
    id: 190,
    country_code: "SC",
    name: "Seychelles",
    dial_code: "+248",
    value: 154,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Seychellois",
    all_inclusive: 0
  },
  {
    id: 192,
    country_code: "SG",
    name: "Singapore",
    dial_code: "+65",
    value: 156,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Singaporean",
    all_inclusive: 0
  },
  {
    id: 193,
    country_code: "SK",
    name: "Slovakia",
    dial_code: "+421",
    value: 157,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Slovak",
    all_inclusive: 0
  },
  {
    id: 194,
    country_code: "SI",
    name: "Slovenia",
    dial_code: "+386",
    value: 158,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Slovenian",
    all_inclusive: 0
  },
  {
    id: 197,
    country_code: "ZA",
    name: "South Africa",
    dial_code: "+27",
    value: 161,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "South African",
    all_inclusive: 0
  },
  {
    id: 199,
    country_code: "ES",
    name: "Spain",
    dial_code: "+34",
    value: 162,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Spanish",
    all_inclusive: 0
  },
  {
    id: 200,
    country_code: "LK",
    name: "Sri Lanka",
    dial_code: "+94",
    value: 163,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Sri Lankan",
    all_inclusive: 0
  },
  {
    id: 207,
    country_code: "SE",
    name: "Sweden",
    dial_code: "+46",
    value: 167,
    currency: "EUR",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "€",
    top_country: false,
    nationality: "Swedish",
    all_inclusive: 0
  },
  {
    id: 208,
    country_code: "CH",
    name: "Switzerland",
    dial_code: "+41",
    value: 168,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "$",
    top_country: false,
    nationality: "Swiss",
    all_inclusive: 0
  },
  {
    id: 210,
    country_code: "TW",
    name: "Taiwan",
    dial_code: "+886",
    value: 170,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Taiwanese",
    all_inclusive: 0
  },
  {
    id: 213,
    country_code: "TH",
    name: "Thailand",
    dial_code: "+66",
    value: 173,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Thai",
    all_inclusive: 0
  },
  {
    id: 79,
    country_code: "GM",
    name: "The Gambia",
    dial_code: "+220",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Gambian",
    all_inclusive: 0
  },
  {
    id: 219,
    country_code: "TR",
    name: "Turkey",
    dial_code: "+90",
    value: 178,
    currency: "USD",
    country_delivery_group_id: 6,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Turkish",
    all_inclusive: 0
  },
  {
    id: 223,
    country_code: "UG",
    name: "Uganda",
    dial_code: "+256",
    value: 181,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Ugandan",
    all_inclusive: 0
  },
  {
    id: 226,
    country_code: "GB",
    name: "United Kingdom",
    dial_code: "+44",
    value: 184,
    currency: "GBP",
    country_delivery_group_id: 6,
    continent: "Europe",
    currency_symbol: "£",
    top_country: true,
    nationality: "British",
    all_inclusive: 0
  },
  {
    id: 212,
    country_code: "TZ",
    name: "United Republic of Tanzania",
    dial_code: "+255",
    value: 1,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Tanazanian",
    all_inclusive: 0
  },
  {
    id: 229,
    country_code: "UZ",
    name: "Uzbekistan",
    dial_code: "+998",
    value: 187,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Uzbek",
    all_inclusive: 0
  },
  {
    id: 230,
    country_code: "VU",
    name: "Vanuatu",
    dial_code: "+678",
    value: 188,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Oceania",
    currency_symbol: "$",
    top_country: false,
    nationality: "Vanuatuan",
    all_inclusive: 0
  },
  {
    id: 233,
    country_code: "VN",
    name: "Vietnam",
    dial_code: "+84",
    value: 191,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Asia",
    currency_symbol: "$",
    top_country: false,
    nationality: "Vietnamese",
    all_inclusive: 0
  },
  {
    id: 242,
    country_code: "ZW",
    name: "Zimbabwe",
    dial_code: "+263",
    value: 197,
    currency: "USD",
    country_delivery_group_id: 5,
    continent: "Africa",
    currency_symbol: "$",
    top_country: false,
    nationality: "Zimbabwean",
    all_inclusive: 0
  }
];
